version: '3'

services:

  kafka-pyclient:
    image: douglascdias/kafka-pyclient
    depends_on:
      - kafka-server
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure

  kafka-server:
    image: douglascdias/kafka-server
    ports:
      - "9092:9092"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
